version: "3.9"

services:
  api:
    build: .
    container_name: korzen-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/korzen
      FLASK_DEBUG: "1"
      PYTHONPATH: /app/src
    depends_on:
      - db

  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.db
    container_name: db
    command: ["postgres", "-c", "shared_preload_libraries=age"]
    environment:
      POSTGRES_DB: korzen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - korzen-db-data:/var/lib/postgresql
      - ./docker/initdb:/docker-entrypoint-initdb.d

volumes:
  korzen-db-data:
