version: "3.9"

services:
  api:
    build: .
    container_name: korzen-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/korzen
      FLASK_DEBUG: "1"
      PYTHONPATH: /app/src
    depends_on:
      - db

  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.db
    container_name: db
    command: ["postgres", "-c", "shared_preload_libraries=age,pg_stat_statements"]
    environment:
      POSTGRES_DB: korzen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - korzen-db-data:/var/lib/postgresql
      - ./docker/initdb:/docker-entrypoint-initdb.d

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/korzen?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db

volumes:
  korzen-db-data:
