"""Initial schema

Revision ID: 9fa49afd5516
Revises: 
Create Date: 2026-05-17 02:55:25.895304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '9fa49afd5516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record1_id', sa.UUID(), nullable=False),
    sa.Column('record2_id', sa.UUID(), nullable=False),
    sa.Column('vector_similarity', sa.Float(), nullable=False),
    sa.Column('phonetic_similarity', sa.Float(), nullable=True),
    sa.Column('date_similarity', sa.Float(), nullable=True),
    sa.Column('location_similarity', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_duplicate_candidates_record1', ['record_type', 'record1_id'], unique=False)
        batch_op.create_index('ix_duplicate_candidates_record2', ['record_type', 'record2_id'], unique=False)
        batch_op.create_index('ix_duplicate_candidates_score', ['composite_score'], unique=False)
        batch_op.create_index('ix_duplicate_candidates_status', ['status'], unique=False)

    op.create_table('record_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latin_name', sa.String(length=100), nullable=False),
    sa.Column('polish_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latin_name')
    )
    op.create_table('duplicate_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('kept_record_id', sa.UUID(), nullable=True),
    sa.Column('merged_record_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('merged_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['duplicate_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genealogical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.String(length=80), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['record_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gedcom_id', sa.String(length=50), nullable=True),
    sa.Column('source_batch_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('maiden_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_date_estimated', sa.Boolean(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('death_date_estimated', sa.Boolean(), nullable=True),
    sa.Column('birth_place', sa.String(length=200), nullable=True),
    sa.Column('death_place', sa.String(length=200), nullable=True),
    sa.Column('residence', sa.String(length=200), nullable=True),
    sa.Column('house_number', sa.String(length=50), nullable=True),
    sa.Column('parish', sa.String(length=200), nullable=True),
    sa.Column('father_id', sa.UUID(), nullable=True),
    sa.Column('mother_id', sa.UUID(), nullable=True),
    sa.Column('social_status_id', sa.UUID(), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
    sa.Column('first_name_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_name_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maiden_name_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['social_status_id'], ['social_statuses.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['record_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_gedcom_id'), ['gedcom_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['record_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baptism_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gedcom_id', sa.String(length=50), nullable=True),
    sa.Column('source_batch_id', sa.UUID(), nullable=True),
    sa.Column('record_number', sa.String(length=50), nullable=True),
    sa.Column('page_number', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('baptism_date', sa.Date(), nullable=False),
    sa.Column('parish', sa.String(length=200), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('house_number', sa.String(length=50), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('child_name', sa.String(length=100), nullable=True),
    sa.Column('child_gender', sa.String(length=10), nullable=True),
    sa.Column('father_id', sa.UUID(), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('father_surname', sa.String(length=100), nullable=True),
    sa.Column('mother_id', sa.UUID(), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('mother_maiden_name', sa.String(length=100), nullable=True),
    sa.Column('legitimate', sa.Boolean(), nullable=True),
    sa.Column('paternal_grandfather_name', sa.String(length=100), nullable=True),
    sa.Column('paternal_grandmother_name', sa.String(length=100), nullable=True),
    sa.Column('maternal_grandfather_name', sa.String(length=100), nullable=True),
    sa.Column('maternal_grandmother_name', sa.String(length=100), nullable=True),
    sa.Column('godfather_name', sa.String(length=100), nullable=True),
    sa.Column('godmother_name', sa.String(length=100), nullable=True),
    sa.Column('godparents_location', sa.String(length=200), nullable=True),
    sa.Column('priest_name', sa.String(length=200), nullable=True),
    sa.Column('original_text_latin', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
    sa.Column('child_name_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('father_surname_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mother_maiden_name_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['father_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['record_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baptism_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baptism_records_gedcom_id'), ['gedcom_id'], unique=False)

    op.create_table('death_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gedcom_id', sa.String(length=50), nullable=True),
    sa.Column('source_batch_id', sa.UUID(), nullable=True),
    sa.Column('record_number', sa.String(length=50), nullable=True),
    sa.Column('page_number', sa.String(length=50), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=False),
    sa.Column('burial_date', sa.Date(), nullable=True),
    sa.Column('parish', sa.String(length=200), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('cemetery', sa.String(length=200), nullable=True),
    sa.Column('deceased_id', sa.UUID(), nullable=True),
    sa.Column('deceased_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_surname', sa.String(length=100), nullable=True),
    sa.Column('deceased_maiden_name', sa.String(length=100), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('age_description', sa.String(length=100), nullable=True),
    sa.Column('cause_of_death', sa.Text(), nullable=True),
    sa.Column('sacraments_received', sa.Boolean(), nullable=True),
    sa.Column('sacraments_details', sa.Text(), nullable=True),
    sa.Column('spouse_name', sa.String(length=100), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('priest_name', sa.String(length=200), nullable=True),
    sa.Column('original_text_latin', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
    sa.Column('deceased_surname_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deceased_maiden_name_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deceased_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['record_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('death_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_death_records_gedcom_id'), ['gedcom_id'], unique=False)

    op.create_table('marriage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gedcom_id', sa.String(length=50), nullable=True),
    sa.Column('source_batch_id', sa.UUID(), nullable=True),
    sa.Column('record_number', sa.String(length=50), nullable=True),
    sa.Column('page_number', sa.String(length=50), nullable=True),
    sa.Column('marriage_date', sa.Date(), nullable=False),
    sa.Column('parish', sa.String(length=200), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('spouse1_id', sa.UUID(), nullable=True),
    sa.Column('spouse1_name', sa.String(length=100), nullable=True),
    sa.Column('spouse1_surname', sa.String(length=100), nullable=True),
    sa.Column('spouse1_status', sa.String(length=50), nullable=True),
    sa.Column('spouse1_parish', sa.String(length=200), nullable=True),
    sa.Column('spouse1_residence', sa.String(length=200), nullable=True),
    sa.Column('spouse1_father_name', sa.String(length=100), nullable=True),
    sa.Column('spouse1_mother_name', sa.String(length=100), nullable=True),
    sa.Column('spouse1_age', sa.Integer(), nullable=True),
    sa.Column('spouse2_id', sa.UUID(), nullable=True),
    sa.Column('spouse2_name', sa.String(length=100), nullable=True),
    sa.Column('spouse2_surname', sa.String(length=100), nullable=True),
    sa.Column('spouse2_maiden_name', sa.String(length=100), nullable=True),
    sa.Column('spouse2_status', sa.String(length=50), nullable=True),
    sa.Column('spouse2_parish', sa.String(length=200), nullable=True),
    sa.Column('spouse2_residence', sa.String(length=200), nullable=True),
    sa.Column('spouse2_father_name', sa.String(length=100), nullable=True),
    sa.Column('spouse2_mother_name', sa.String(length=100), nullable=True),
    sa.Column('spouse2_age', sa.Integer(), nullable=True),
    sa.Column('banns_count', sa.Integer(), nullable=True),
    sa.Column('banns_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('witnesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priest_name', sa.String(length=200), nullable=True),
    sa.Column('original_text_latin', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
    sa.Column('spouse1_surname_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spouse2_surname_phonetic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_batch_id'], ['record_batches.id'], ),
    sa.ForeignKeyConstraint(['spouse1_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['spouse2_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marriage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marriage_records_gedcom_id'), ['gedcom_id'], unique=False)

    op.create_table('godparent_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baptism_record_id', sa.UUID(), nullable=False),
    sa.Column('godparent_id', sa.UUID(), nullable=False),
    sa.Column('godparent_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baptism_record_id'], ['baptism_records.id'], ),
    sa.ForeignKeyConstraint(['godparent_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('witness_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marriage_record_id', sa.UUID(), nullable=False),
    sa.Column('witness_id', sa.UUID(), nullable=False),
    sa.Column('witness_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marriage_record_id'], ['marriage_records.id'], ),
    sa.ForeignKeyConstraint(['witness_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('witness_relationships')
    op.drop_table('godparent_relationships')
    with op.batch_alter_table('marriage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marriage_records_gedcom_id'))

    op.drop_table('marriage_records')
    with op.batch_alter_table('death_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_death_records_gedcom_id'))

    op.drop_table('death_records')
    with op.batch_alter_table('baptism_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baptism_records_gedcom_id'))

    op.drop_table('baptism_records')
    op.drop_table('uploaded_files')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_gedcom_id'))

    op.drop_table('persons')
    op.drop_table('genealogical_records')
    op.drop_table('duplicate_resolutions')
    op.drop_table('social_statuses')
    op.drop_table('record_batches')
    with op.batch_alter_table('duplicate_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_duplicate_candidates_status')
        batch_op.drop_index('ix_duplicate_candidates_score')
        batch_op.drop_index('ix_duplicate_candidates_record2')
        batch_op.drop_index('ix_duplicate_candidates_record1')

    op.drop_table('duplicate_candidates')
    # ### end Alembic commands ###
