"""empty message

Revision ID: a1507a155ff3
Revises: add_gedcom_id_001
Create Date: 2026-05-16 19:17:40.522960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1507a155ff3'
down_revision = 'add_gedcom_id_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gedcom_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_batch_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_persons_gedcom_id'), ['gedcom_id'], unique=False)
        batch_op.create_foreign_key(None, 'record_batches', ['source_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_persons_gedcom_id'))
        batch_op.drop_column('source_batch_id')
        batch_op.drop_column('gedcom_id')

    # ### end Alembic commands ###
