"""add_cascade_delete_to_person_fks

Revision ID: ce299e9dbdee
Revises: 9fa49afd5516
Create Date: 2026-05-17 17:02:01.752865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce299e9dbdee'
down_revision = '9fa49afd5516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip AGE table operations - they are managed by Apache AGE extension
    
    with op.batch_alter_table('baptism_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('baptism_records_child_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('baptism_records_mother_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('baptism_records_father_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['father_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'persons', ['child_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'persons', ['mother_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('death_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('death_records_deceased_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['deceased_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('godparent_relationships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('godparent_relationships_godparent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['godparent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('marriage_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('marriage_records_spouse2_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('marriage_records_spouse1_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['spouse2_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'persons', ['spouse1_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('persons_father_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('persons_mother_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['mother_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'persons', ['father_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('witness_relationships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('witness_relationships_witness_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['witness_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip AGE table operations - they are managed by Apache AGE extension
    
    with op.batch_alter_table('witness_relationships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('witness_relationships_witness_id_fkey'), 'persons', ['witness_id'], ['id'])

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('persons_mother_id_fkey'), 'persons', ['mother_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('persons_father_id_fkey'), 'persons', ['father_id'], ['id'])

    with op.batch_alter_table('marriage_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('marriage_records_spouse1_id_fkey'), 'persons', ['spouse1_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('marriage_records_spouse2_id_fkey'), 'persons', ['spouse2_id'], ['id'])

    with op.batch_alter_table('godparent_relationships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('godparent_relationships_godparent_id_fkey'), 'persons', ['godparent_id'], ['id'])

    with op.batch_alter_table('death_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('death_records_deceased_id_fkey'), 'persons', ['deceased_id'], ['id'])

    with op.batch_alter_table('baptism_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('baptism_records_father_id_fkey'), 'persons', ['father_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('baptism_records_mother_id_fkey'), 'persons', ['mother_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('baptism_records_child_id_fkey'), 'persons', ['child_id'], ['id'])
    
    # ### end Alembic commands ###
